branch-defaults:
  master:
    environment: Default-Environment
environment-defaults:
  Default-Environment:
    branch: null
    repository: null
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/3.3.1
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
